<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIIjXoJh\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIIjXoJh/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerIIjXoJh.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerIIjXoJh\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerIIjXoJh\appAppKernelProdContainer([
    'container.build_hash' => 'IIjXoJh',
    'container.build_id' => '051702b1',
    'container.build_time' => 1683172036,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIIjXoJh');
